% -------------------------------------------------------------------
%  Generated by MATLAB on 14-Jun-2021 09:37:23
%  MATLAB version: 9.10.0.1649659 (R2021a) Update 1
% -------------------------------------------------------------------
                                               

aeroCoeff = struct;
aeroCoeff.Cl0 = 0;
aeroCoeff.Cl_beta = -0.036269164;
aeroCoeff.Cl_da = -0.1109919434;
aeroCoeff.Cl_dr = 0.1739783018;
aeroCoeff.Cl_p = -0.7949096926;
aeroCoeff.Cl_r = 0.2014971632;
aeroCoeff.Cm0 = 0;
aeroCoeff.Cm_alpha = 1.2064499223;
aeroCoeff.Cm_de = 2.1428321197;
aeroCoeff.Cm_q = -45.8054617420;
aeroCoeff.Cn0 = 0;
aeroCoeff.Cn_beta = 0.0488691990;
aeroCoeff.Cn_da = 0.0182026787;
aeroCoeff.Cn_dr = -0.3910440741;
aeroCoeff.Cn_p = -0.0359727396;
aeroCoeff.Cn_r = -0.0735610276;
aeroCoeff.Cx0 = 0;
aeroCoeff.Cx_alpha = 0.4794149837;
aeroCoeff.Cx_q = 0;
aeroCoeff.Cx_de = 0;
aeroCoeff.Cy0 = 0;
aeroCoeff.Cy_beta = -0.1609874369;
aeroCoeff.Cy_da = 0;
aeroCoeff.Cy_dr = 0.9151416544;
aeroCoeff.Cy_p = -0.0237997869;
aeroCoeff.Cy_r = 0.1375812867;
aeroCoeff.Cz0 = -0.7380651028;
aeroCoeff.Cz_alpha = -4.3137874942;
aeroCoeff.Cz_de = -0.8059095299;
aeroCoeff.Cz_q = 1.1314080467;
aeroCoeff.Cx_u = -0.2238699661;
aeroCoeff.Cz_u = -0.0315213744;
aeroCoeff.Cm_u = 0.0310001077;
aeroCoeff.Cx_adot = 0.0000000000;
aeroCoeff.Cz_adot = -4.0923453343;
aeroCoeff.Cm_adot =-14.0808879368;
aeroCoeff.V0 = 64.7238942891;


environment = struct;
environment.EarthRefAlt = 0;

initCond = struct;
initCond.x0 = [0 0 -1000];
initCond.v0 = [64.7238942891 0 0];
initCond.euler0 = [0 0 0];
initCond.w0 = [0 0 0];

inputs0 = struct;
inputs0.time = 0;
inputs0.signals = struct;
inputs0.signals(1).dimensions = 1;
inputs0.signals(1).values = -0.104711430293605;
inputs0.signals(2).dimensions = 1;
inputs0.signals(2).values = -0.069872522954441;
inputs0.signals(3).dimensions = 1;
inputs0.signals(3).values = -0.000215042330254086;

states0 = struct;
states0.time = 0;
states0.signals = struct;
states0.signals(1).values = [0 0 -1000];
states0.signals(1).dimensions = 3;
states0.signals(1).label = 'CSTATE';
states0.signals(1).blockName = ['asb6DOFAirframeTemplate/6DOF EOM/6DOF ' ...
                                '(Euler Angles)/xe,ye,ze'];
states0.signals(1).stateName = '';
states0.signals(1).inReferencedModel = false;
states0.signals(1).sampleTime = [0 0];
states0.signals(2).values = [0.128665353088755 0.25933765994587 -0.178947917154394 ...
                             ];
states0.signals(2).dimensions = 3;
states0.signals(2).label = 'CSTATE';
states0.signals(2).blockName = ['asb6DOFAirframeTemplate/6DOF EOM/6DOF ' ...
                                '(Euler Angles)/Calculate DCM &', char(10), '' ...
                                'Euler Angles/phi', char(10), 'theta', char(10), '' ...
                                'psi'];
states0.signals(2).stateName = '';
states0.signals(2).inReferencedModel = false;
states0.signals(2).sampleTime = [0 0];
states0.signals(3).values = [36.911969266574353 8.1072086326441184 8.82591882596406 ...
                             ];
states0.signals(3).dimensions = 3;
states0.signals(3).label = 'CSTATE';
states0.signals(3).blockName = ['asb6DOFAirframeTemplate/6DOF EOM/6DOF ' ...
                                '(Euler Angles)/ub,vb,wb'];
states0.signals(3).stateName = '';
states0.signals(3).inReferencedModel = false;
states0.signals(3).sampleTime = [0 0];
states0.signals(4).values = [0 0 0];
states0.signals(4).dimensions = 3;
states0.signals(4).label = 'CSTATE';
states0.signals(4).blockName = ['asb6DOFAirframeTemplate/6DOF EOM/6DOF ' ...
                                '(Euler Angles)/p,q,r '];
states0.signals(4).stateName = '';
states0.signals(4).inReferencedModel = false;
states0.signals(4).sampleTime = [0 0];
states0.signals(5).values = [0 0];
states0.signals(5).dimensions = 2;
states0.signals(5).label = 'CSTATE';
states0.signals(5).blockName = ['asb6DOFAirframeTemplate/Environment Mo' ...
                                'del/Dryden Wind Turbulence Model ', char(10), '' ...
                                '(Continuous (+q +r))/Filters on veloci' ...
                                'ties/Hwgw(s)/wg_p1'];
states0.signals(5).stateName = '';
states0.signals(5).inReferencedModel = false;
states0.signals(5).sampleTime = [0 0];
states0.signals(6).values = [0 0];
states0.signals(6).dimensions = 2;
states0.signals(6).label = 'CSTATE';
states0.signals(6).blockName = ['asb6DOFAirframeTemplate/Environment Mo' ...
                                'del/Dryden Wind Turbulence Model ', char(10), '' ...
                                '(Continuous (+q +r))/Filters on veloci' ...
                                'ties/Hwgw(s)/wg_p2'];
states0.signals(6).stateName = '';
states0.signals(6).inReferencedModel = false;
states0.signals(6).sampleTime = [0 0];
states0.signals(7).values = [0 0];
states0.signals(7).dimensions = 2;
states0.signals(7).label = 'CSTATE';
states0.signals(7).blockName = ['asb6DOFAirframeTemplate/Environment Mo' ...
                                'del/Dryden Wind Turbulence Model ', char(10), '' ...
                                '(Continuous (+q +r))/Filters on veloci' ...
                                'ties/Hvgw(s)/vg_p1'];
states0.signals(7).stateName = '';
states0.signals(7).inReferencedModel = false;
states0.signals(7).sampleTime = [0 0];
states0.signals(8).values = [0 0];
states0.signals(8).dimensions = 2;
states0.signals(8).label = 'CSTATE';
states0.signals(8).blockName = ['asb6DOFAirframeTemplate/Environment Mo' ...
                                'del/Dryden Wind Turbulence Model ', char(10), '' ...
                                '(Continuous (+q +r))/Filters on veloci' ...
                                'ties/Hvgw(s)/vgw_p2'];
states0.signals(8).stateName = '';
states0.signals(8).inReferencedModel = false;
states0.signals(8).sampleTime = [0 0];
states0.signals(9).values = [0 0];
states0.signals(9).dimensions = 2;
states0.signals(9).label = 'CSTATE';
states0.signals(9).blockName = ['asb6DOFAirframeTemplate/Environment Mo' ...
                                'del/Dryden Wind Turbulence Model ', char(10), '' ...
                                '(Continuous (+q +r))/Filters on veloci' ...
                                'ties/Hugw(s)/ug_p'];
states0.signals(9).stateName = '';
states0.signals(9).inReferencedModel = false;
states0.signals(9).sampleTime = [0 0];
states0.signals(10).values = [0 0];
states0.signals(10).dimensions = 2;
states0.signals(10).label = 'CSTATE';
states0.signals(10).blockName = ['asb6DOFAirframeTemplate/Environment M' ...
                                 'odel/Dryden Wind Turbulence Model ', char(10), '' ...
                                 '(Continuous (+q +r))/Filters on angul' ...
                                 'ar rates/Hrgw/rgw_p'];
states0.signals(10).stateName = '';
states0.signals(10).inReferencedModel = false;
states0.signals(10).sampleTime = [0 0];
states0.signals(11).values = [0 0];
states0.signals(11).dimensions = 2;
states0.signals(11).label = 'CSTATE';
states0.signals(11).blockName = ['asb6DOFAirframeTemplate/Environment M' ...
                                 'odel/Dryden Wind Turbulence Model ', char(10), '' ...
                                 '(Continuous (+q +r))/Filters on angul' ...
                                 'ar rates/Hqgw/qgw_p'];
states0.signals(11).stateName = '';
states0.signals(11).inReferencedModel = false;
states0.signals(11).sampleTime = [0 0];
states0.signals(12).values = [0 0];
states0.signals(12).dimensions = 2;
states0.signals(12).label = 'CSTATE';
states0.signals(12).blockName = ['asb6DOFAirframeTemplate/Environment M' ...
                                 'odel/Dryden Wind Turbulence Model ', char(10), '' ...
                                 '(Continuous (+q +r))/Filters on angul' ...
                                 'ar rates/Hpgw/pgw_p'];
states0.signals(12).stateName = '';
states0.signals(12).inReferencedModel = false;
states0.signals(12).sampleTime = [0 0];

vehicle = struct;
vehicle.Sref = 16.8342275746;
vehicle.cbar = 1.0141293678;
vehicle.bref = 8.7036787674;
vehicle.CG = [0 0 0];
vehicle.CP = [0 0 0];
vehicle.inertia = ...
  [11509.7158987289 0 121.1637017489;
   0 19890.9477240270 0;
   -121.1637017489 0 28644.1528968915 ];
vehicle.acMass = 2950;
vehicle.Thrust = 2300;
vehicle.aileron_max = deg2rad(30);
vehicle.aileron_min = -deg2rad(30);
vehicle.elevator_max = deg2rad(17.5);
vehicle.elevator_min = -deg2rad(17.5);
vehicle.rudder_max = deg2rad(25);
vehicle.rudder_min = -deg2rad(25);

