from dataclasses import dataclass
import GeneralConstants as constants
import sys 
import pathlib as pl

sys.path.append(str(list(pl.Path(__file__).parents)[0]))



@dataclass
class FuelCell:
    """
    This class is to estimate the parameters of a Fuel Cell.

    :param PowerDensity: Power density [kW/kg]
    :param VolumeDensity: Volumetric energy density [kWh/l]
    :param Cost: Cost of the fuel cell [US$] (not loaded)
    :param Efficiency: Efficiency of the fuel cell 
    :param operating_temperature[K]
    """
    powerDensity: float = None
    volumeDensity: float  = None
    cost: float = None
    efficiency: float = None
    operating_temperature : float = None

    def load(self):
        self.powerDensity = constants.PowerDensityFuellCell
        self.volumeDensity = constants.VolumeDensityFuellCell
        self.efficiency = constants.effiencyFuellCell

    def mass(self,power):
        """
        :param: power [kW]
        :return: Mass of the battery
        """
        return power / self.PowerDensity

    def volume(self,power):
        """
        :param: power [kW]
        :return: Volume of the fuell cell [m^3]
        """
        return power /self.VolumeDensity  * 0.001

    def price(self,power):
        """
        :param: power [kW]
        :return: Approx cost of the battery [US$]
        """
        return power * self.Cost

    def heat(self, power):
        """
        :param: power[kW]: electric power generated by the fuel cell
        :return: heat generated by the fuel cell
        """
        return (1 - self.efficiency)/ self.efficiency * power
