% -------------------------------------------------------------------
%  Generated by MATLAB on 14-Jun-2021 09:37:23
%  MATLAB version: 9.10.0.1649659 (R2021a) Update 1
% -------------------------------------------------------------------
                                               

aeroCoeff = struct;
aeroCoeff.Cl0 = 0;
aeroCoeff.Cl_beta = -0.0772;
aeroCoeff.Cl_da = -0.2349;
aeroCoeff.Cl_dr = 0.0286;
aeroCoeff.Cl_p = -0.3444;
aeroCoeff.Cl_r = 0.28;
aeroCoeff.Cm0 = 0;
aeroCoeff.Cm_alpha = -0.43;
aeroCoeff.Cm_alpha_dot = -3.7;
aeroCoeff.Cm_de = -1.553;
aeroCoeff.Cm_q = -7.04;
aeroCoeff.Cm_u = 0;
aeroCoeff.Cn0 = 0;
aeroCoeff.Cn_beta = 0.1638;
aeroCoeff.Cn_beta_dot = 0;
aeroCoeff.Cn_da = 0.0286;
aeroCoeff.Cn_dr = -0.1261;
aeroCoeff.Cn_p = -0.0108;
aeroCoeff.Cn_r = -0.193;
aeroCoeff.Cx0 = 0;
aeroCoeff.Cx_alpha = 0.4653;
aeroCoeff.Cx_alpha_dot = 0.0000000000;
aeroCoeff.Cx_q = 0;
aeroCoeff.Cx_u = -0.2199;
aeroCoeff.Cx_de = 0;
aeroCoeff.Cy0 = 0;
aeroCoeff.Cy_beta = -0.9896;
aeroCoeff.Cy_beta_dot = 0;
aeroCoeff.Cy_da = 0;
aeroCoeff.Cy_dr = 0.3037;
aeroCoeff.Cy_p = -0.0870;
aeroCoeff.Cy_r = 0.43;
aeroCoeff.Cz0 = -1.136;
aeroCoeff.Cz_alpha = -5.16;
aeroCoeff.Cz_alpha_dot = 1.43;
aeroCoeff.Cz_de = -0.6238;
aeroCoeff.Cz_q = -3.86;
aeroCoeff.Cz_u = -2.272;

aeroCoeff.CL = 1.136;

initCond = struct;
initCond.x0 = [0 0 -1000];
initCond.v0 = 59.9;
initCond.euler0 = [0 0 0];
initCond.w0 = [0 0 0];

vehicle = struct;
vehicle.Sref = 24.2;
vehicle.cbar = 2.022;
vehicle.bref = 13.36;
vehicle.Kxx = 0.012;
vehicle.Kyy = 0.98;
vehicle.Kzz = 0.037;
vehicle.Kxz = 0.002;
vehicle.mu_c = 102.7;
vehicle.mu_b = 15.5;
vehicle.aileron_max = deg2rad(30);
vehicle.aileron_min = -deg2rad(30);
vehicle.elevator_max = deg2rad(17.5);
vehicle.elevator_min = -deg2rad(17.5);
vehicle.rudder_max = deg2rad(25);
vehicle.rudder_min = -deg2rad(25);

symmSys = struct;
symmSys.P = [-2 * vehicle.mu_c * vehicle.cbar / initCond.v0 0 0 0;
            0 (aeroCoeff.Cz_alpha_dot - 2 * vehicle.mu_c) * vehicle.cbar / initCond.v0 0 0;
            0 0 -vehicle.cbar / initCond.v0 0;
            0 aeroCoeff.Cm_alpha_dot * vehicle.cbar / initCond.v0 0 -2 * vehicle.mu_c * vehicle.Kyy * vehicle.cbar / initCond.v0];

symmSys.Q = [-aeroCoeff.Cx_u -aeroCoeff.Cx_alpha -aeroCoeff.Cz0 0;
            -aeroCoeff.Cz_u -aeroCoeff.Cz_alpha aeroCoeff.Cx0 -(aeroCoeff.Cz_q + 2 * vehicle.mu_c);
            0 0 0 -1;
            -aeroCoeff.Cm_u -aeroCoeff.Cm_alpha 0 -aeroCoeff.Cm_q];

symmSys.R = [-aeroCoeff.Cx_de;
            -aeroCoeff.Cz_de;
            0;
            -aeroCoeff.Cm_de];

symmSys.A = inv(symmSys.P) * symmSys.Q;
symmSys.B = inv(symmSys.P) * symmSys.R;

asymmSys = struct;
asymmSys.P = [(aeroCoeff.Cy_beta_dot - 2 * vehicle.mu_b) * vehicle.bref / initCond.v0 0 0 0;
              0 -1/2 * vehicle.bref / initCond.v0 0 0;
              0 0 -4 * vehicle.mu_b * vehicle.Kxx * vehicle.bref / initCond.v0 4 * vehicle.mu_b * vehicle.Kxz * vehicle.bref / initCond.v0;
              aeroCoeff.Cn_beta_dot * vehicle.bref / initCond.v0 0 4 * vehicle.mu_b * vehicle.Kxz * vehicle.bref / initCond.v0 -4 * vehicle.mu_b * vehicle.Kzz * vehicle.bref / initCond.v0];

asymmSys.Q = [-aeroCoeff.Cy_beta -aeroCoeff.CL -aeroCoeff.Cy_p -(aeroCoeff.Cy_r - 4 * vehicle.mu_b);
              0 0 -1 0;
              -aeroCoeff.Cl_beta 0 -aeroCoeff.Cl_p -aeroCoeff.Cl_r;
              -aeroCoeff.Cn_beta 0 -aeroCoeff.Cn_p -aeroCoeff.Cn_r];

asymmSys.R = [-aeroCoeff.Cy_da -aeroCoeff.Cy_dr;
              0 0;
              -aeroCoeff.Cl_da -aeroCoeff.Cl_dr;
              -aeroCoeff.Cn_da -aeroCoeff.Cn_dr];

asymmSys.A = inv(asymmSys.P) * asymmSys.Q;
asymmSys.B = inv(asymmSys.P) * asymmSys.R;
