% -------------------------------------------------------------------
%  Generated by MATLAB on 16-Jun-2021 09:57:05
%  MATLAB version: 9.10.0.1649659 (R2021a) Update 1
% -------------------------------------------------------------------
                                                                    

aeroCoeff = struct;
aeroCoeff.Cl0 = 0;
aeroCoeff.Cl_beta = -0.0772;
aeroCoeff.Cl_da = -0.2349;
aeroCoeff.Cl_da_alpha = 0;
aeroCoeff.Cl_dr = 0.0286;
aeroCoeff.Cl_p = -0.3444;
aeroCoeff.Cl_r = 0.28;
aeroCoeff.Cm0 = 0;
aeroCoeff.Cm_alpha = -0.43;
aeroCoeff.Cm_alpha2 = 0;
aeroCoeff.Cm_alpha_dot = -3.7;
aeroCoeff.Cm_beta2 = 0;
aeroCoeff.Cm_de = -1.553;
aeroCoeff.Cm_df = 0;
aeroCoeff.Cm_q = -7.04;
aeroCoeff.Cm_r = 0;
aeroCoeff.Cm_u = 0;
aeroCoeff.Cn0 = 0;
aeroCoeff.Cn_beta = 0.1638;
aeroCoeff.Cn_beta3 = 0;
aeroCoeff.Cn_da = 0.0286;
aeroCoeff.Cn_dr = -0.1261;
aeroCoeff.Cn_p = -0.0108;
aeroCoeff.Cn_q = 0;
aeroCoeff.Cn_r = -0.193;
aeroCoeff.Cx0 = 0;
aeroCoeff.Cx_alpha = 0.4653;
aeroCoeff.Cx_alpha_dot = 0;
aeroCoeff.Cx_alpha2 = 0;
aeroCoeff.Cx_alpha3 = 0;
aeroCoeff.Cx_de = 0;
aeroCoeff.Cx_df = 0;
aeroCoeff.Cx_df_alpha = 0;
aeroCoeff.Cx_dr = 0;
aeroCoeff.Cx_q = 0;
aeroCoeff.Cx_u = -0.2199;
aeroCoeff.Cy0 = 0;
aeroCoeff.Cy_beta = -0.9896;
aeroCoeff.Cy_da = 0;
aeroCoeff.Cy_dr = 0.3037;
aeroCoeff.Cy_dr_alpha = 0;
aeroCoeff.Cy_p = -0.087;
aeroCoeff.Cy_r = 0.43;
aeroCoeff.Cz0 = -1.136;
aeroCoeff.Cz_alpha = -5.16;
aeroCoeff.Cz_alpha3 = 3.442;
aeroCoeff.Cz_alpha_dot = -1.43;
aeroCoeff.Cz_de = -0.6238;
aeroCoeff.Cz_de_beta = 0;
aeroCoeff.Cz_df = 0;
aeroCoeff.Cz_df_alpha = 0;
aeroCoeff.Cz_q = -3.86;
aeroCoeff.Cz_u = -2.272;

environment = struct;
environment.EarthRefAlt = 0;

initCond = struct;
initCond.x0 = [0 0 -500];
initCond.v0 = [59.9 0 0];
initCond.euler0 = [0 0 0];
initCond.w0 = [0 0 0];

inputs0 = struct;
inputs0.time = 0;
inputs0.signals = struct;
inputs0.signals(1).dimensions = 1;
inputs0.signals(1).values = -0.104711430293605;
inputs0.signals(2).dimensions = 1;
inputs0.signals(2).values = -0.069872522954441;
inputs0.signals(3).dimensions = 1;
inputs0.signals(3).values = -0.000215042330254086;

states0 = struct;
states0.time = 0;
states0.signals = struct;
states0.signals(1).values = initCond.x0;
states0.signals(1).dimensions = 3;
states0.signals(1).label = 'CSTATE';
states0.signals(1).blockName = ['asb6DOFAirframeTemplate/6DOF EOM/6DOF ' ...
                                '(Euler Angles)/xe,ye,ze'];
states0.signals(1).stateName = '';
states0.signals(1).inReferencedModel = false;
states0.signals(1).sampleTime = [0 0];
states0.signals(2).values = initCond.euler0;
states0.signals(2).dimensions = 3;
states0.signals(2).label = 'CSTATE';
states0.signals(2).blockName = ['asb6DOFAirframeTemplate/6DOF EOM/6DOF ' ...
                                '(Euler Angles)/Calculate DCM &', char(10), '' ...
                                'Euler Angles/phi', char(10), 'theta', char(10), '' ...
                                'psi'];
states0.signals(2).stateName = '';
states0.signals(2).inReferencedModel = false;
states0.signals(2).sampleTime = [0 0];
states0.signals(3).values = initCond.v0;
states0.signals(3).dimensions = 3;
states0.signals(3).label = 'CSTATE';
states0.signals(3).blockName = ['asb6DOFAirframeTemplate/6DOF EOM/6DOF ' ...
                                '(Euler Angles)/ub,vb,wb'];
states0.signals(3).stateName = '';
states0.signals(3).inReferencedModel = false;
states0.signals(3).sampleTime = [0 0];
states0.signals(4).values = [0 0 0];
states0.signals(4).dimensions = 3;
states0.signals(4).label = 'CSTATE';
states0.signals(4).blockName = ['asb6DOFAirframeTemplate/6DOF EOM/6DOF ' ...
                                '(Euler Angles)/p,q,r '];
states0.signals(4).stateName = '';
states0.signals(4).inReferencedModel = false;
states0.signals(4).sampleTime = [0 0];
states0.signals(5).values = [0 0];
states0.signals(5).dimensions = 2;
states0.signals(5).label = 'CSTATE';
states0.signals(5).blockName = ['asb6DOFAirframeTemplate/Environment Mo' ...
                                'del/Dryden Wind Turbulence Model ', char(10), '' ...
                                '(Continuous (+q +r))/Filters on veloci' ...
                                'ties/Hwgw(s)/wg_p1'];
states0.signals(5).stateName = '';
states0.signals(5).inReferencedModel = false;
states0.signals(5).sampleTime = [0 0];
states0.signals(6).values = [0 0];
states0.signals(6).dimensions = 2;
states0.signals(6).label = 'CSTATE';
states0.signals(6).blockName = ['asb6DOFAirframeTemplate/Environment Mo' ...
                                'del/Dryden Wind Turbulence Model ', char(10), '' ...
                                '(Continuous (+q +r))/Filters on veloci' ...
                                'ties/Hwgw(s)/wg_p2'];
states0.signals(6).stateName = '';
states0.signals(6).inReferencedModel = false;
states0.signals(6).sampleTime = [0 0];
states0.signals(7).values = [0 0];
states0.signals(7).dimensions = 2;
states0.signals(7).label = 'CSTATE';
states0.signals(7).blockName = ['asb6DOFAirframeTemplate/Environment Mo' ...
                                'del/Dryden Wind Turbulence Model ', char(10), '' ...
                                '(Continuous (+q +r))/Filters on veloci' ...
                                'ties/Hvgw(s)/vg_p1'];
states0.signals(7).stateName = '';
states0.signals(7).inReferencedModel = false;
states0.signals(7).sampleTime = [0 0];
states0.signals(8).values = [0 0];
states0.signals(8).dimensions = 2;
states0.signals(8).label = 'CSTATE';
states0.signals(8).blockName = ['asb6DOFAirframeTemplate/Environment Mo' ...
                                'del/Dryden Wind Turbulence Model ', char(10), '' ...
                                '(Continuous (+q +r))/Filters on veloci' ...
                                'ties/Hvgw(s)/vgw_p2'];
states0.signals(8).stateName = '';
states0.signals(8).inReferencedModel = false;
states0.signals(8).sampleTime = [0 0];
states0.signals(9).values = [0 0];
states0.signals(9).dimensions = 2;
states0.signals(9).label = 'CSTATE';
states0.signals(9).blockName = ['asb6DOFAirframeTemplate/Environment Mo' ...
                                'del/Dryden Wind Turbulence Model ', char(10), '' ...
                                '(Continuous (+q +r))/Filters on veloci' ...
                                'ties/Hugw(s)/ug_p'];
states0.signals(9).stateName = '';
states0.signals(9).inReferencedModel = false;
states0.signals(9).sampleTime = [0 0];
states0.signals(10).values = [0 0];
states0.signals(10).dimensions = 2;
states0.signals(10).label = 'CSTATE';
states0.signals(10).blockName = ['asb6DOFAirframeTemplate/Environment M' ...
                                 'odel/Dryden Wind Turbulence Model ', char(10), '' ...
                                 '(Continuous (+q +r))/Filters on angul' ...
                                 'ar rates/Hrgw/rgw_p'];
states0.signals(10).stateName = '';
states0.signals(10).inReferencedModel = false;
states0.signals(10).sampleTime = [0 0];
states0.signals(11).values = [0 0];
states0.signals(11).dimensions = 2;
states0.signals(11).label = 'CSTATE';
states0.signals(11).blockName = ['asb6DOFAirframeTemplate/Environment M' ...
                                 'odel/Dryden Wind Turbulence Model ', char(10), '' ...
                                 '(Continuous (+q +r))/Filters on angul' ...
                                 'ar rates/Hqgw/qgw_p'];
states0.signals(11).stateName = '';
states0.signals(11).inReferencedModel = false;
states0.signals(11).sampleTime = [0 0];
states0.signals(12).values = [0 0];
states0.signals(12).dimensions = 2;
states0.signals(12).label = 'CSTATE';
states0.signals(12).blockName = ['asb6DOFAirframeTemplate/Environment M' ...
                                 'odel/Dryden Wind Turbulence Model ', char(10), '' ...
                                 '(Continuous (+q +r))/Filters on angul' ...
                                 'ar rates/Hpgw/pgw_p'];
states0.signals(12).stateName = '';
states0.signals(12).inReferencedModel = false;
states0.signals(12).sampleTime = [0 0];

vehicle = struct;
vehicle.Sref = 24.2;
vehicle.cbar = 2.022;
vehicle.bref = 13.36;
vehicle.CG = [0 0 0];
vehicle.CP = [0 0 0];
vehicle.inertia = ...
  [0.012*4547.8*13.36^2 0 0.002*4547.8*13.36^2;
   0 0.98*4547.8*2.022^2 0;
   -0.002*4547.8*13.36^2 0 0.037*4547.8*13.36^2];
vehicle.acMass = 4547.8;
vehicle.Thrust = 0;
% TODO: maybe change these?
vehicle.aileron_max = 0.52359877559829882;
vehicle.aileron_min = -0.52359877559829882;
vehicle.elevator_max = 0.52359877559829882;
vehicle.elevator_min = -0.52359877559829882;
vehicle.rudder_max = 1.0471975511965976;
vehicle.rudder_min = -1.0471975511965976;

